### ISSUE TITLE
The "VST Binary location" build configuration setting is not supported

### ISSUE THREAD

**Issue by McMartin** [McMartin/JUCE.cmake#174]
This setting is only relevant for VST Audio Plug-in projects.

**Comment by MartyLake** [comment]
We switched to this build system. This issue still modifies the way we worked because Introjucer has been providing a default post build script to install the VST for shorter code-compile-run loop.

**Comment by McMartin** [comment]
@MartyLake: please try the branch [support-binary-location-settings](https://github.com/McMartin/JUCE.cmake/tree/support-binary-location-settings) and tell me if it works for you as expected, thanks!

**Comment by WGuLL** [comment]
@McMartin Hi ! Unfortunately, it did not work as expected. I got this error: 
```
CMake Error at /Generated/JUCE.cmake/cmake/Reprojucer.cmake:829 (set_target_properties):
  set_target_properties called with incorrect number of arguments.
Call Stack (most recent call first):
  CMakeLists.txt:798 (jucer_project_end)


CMake Error at /Generated/JUCE.cmake/cmake/Reprojucer.cmake:829 (set_target_properties):
  set_target_properties called with incorrect number of arguments.
Call Stack (most recent call first):
  CMakeLists.txt:798 (jucer_project_end)


CMake Error at /Generated/JUCE.cmake/cmake/Reprojucer.cmake:895 (set_target_properties):
  set_target_properties called with incorrect number of arguments.
Call Stack (most recent call first):
  CMakeLists.txt:798 (jucer_project_end)


CMake Error at /Generated/JUCE.cmake/cmake/Reprojucer.cmake:895 (set_target_properties):
  set_target_properties called with incorrect number of arguments.
Call Stack (most recent call first):
  CMakeLists.txt:798 (jucer_project_end)```

**Comment by McMartin** [comment]
This problem was already reported by @MartyLake here: https://github.com/McMartin/JUCE.cmake/commit/32c7ac4cf5c7d126e3e8703d32ba80ece43d01e6#commitcomment-22485985 and I normally fixed it in the latest version of the branch. @WGuLL, can you make sure that you are using the current version of the branch [support-binary-location-settings](https://github.com/McMartin/JUCE.cmake/tree/support-binary-location-settings)?

**Comment by WGuLL** [comment]
I tried with this commit 94cd2e0 but I had the same error. 9222100 was applied on the version I was using for sure.

**Comment by McMartin** [comment]
@WGuLL I figured out what was going on and I pushed two next fixup commits (f9f34cee8f60c9f94f3cccb040a28e9cdcf06f28 and 4aee42c36dafd69a7eaf821f53ea908bf9776282).

**Comment by McMartin** [comment]
@WGuLL: I found more bugs (see #185 for instance) and I fixed them. Please try again with the latest version of the branch (https://github.com/McMartin/JUCE.cmake/tree/support-binary-location-settings), and tell me if something still doesn't work for you, thanks!

**Comment by WGuLL** [comment]
@McMartin I tried with a0e19f2. Everything seems to work ! Thanks ! 👍

**Comment by McMartin** [comment]
@WGuLL thank you for testing. I will double-check that the implemented behavior matches what the Projucer does and then open a PR to integrate these changes.

**Comment by McMartin** [comment]
@WGuLL: I reworked the branch to add making a symlink from the build folder to the VST Binary location like the Projucer does. Please have a look at https://github.com/McMartin/JUCE.cmake/pull/190.
