### ISSUE TITLE
The "AU Binary location" build configuration setting is not supported

### ISSUE THREAD

**Issue by McMartin** [McMartin/JUCE.cmake#175]
This setting is only relevant for AU Audio Plug-in projects.

**Comment by MartyLake** [comment]
We switched to this build system. This issue still modifies the way we worked because Introjucer has been providing a default post build script to install the AU for shorter code-compile-run loop.

**Comment by McMartin** [comment]
@MartyLake: please try the branch [support-binary-location-settings](https://github.com/McMartin/JUCE.cmake/tree/support-binary-location-settings) and tell me if it works for you as expected, thanks!
