### ISSUE TITLE
Missing xcode resource not ignored on Windows.

### ISSUE THREAD

**Issue by WGuLL** [McMartin/JUCE.cmake#193]
Our project has a generated file used as an xcode resource on osx. On windows this file is not generated.
On windows, project generation fails because the xcode resource is missing. A work around for this issue is to generate an empty file in place of the resource before generating the project.

**Comment by McMartin** [comment]
@WGuLL: I am sorry for that bug. It should be fixed by https://github.com/McMartin/JUCE.cmake/pull/194,
