### ISSUE TITLE
Building with no "debug/release" explicitely throws warnings

### ISSUE THREAD

**Issue by MartyLake** [McMartin/JUCE.cmake#20]
steps to reproduce (OSX 10.9):

```
git clone --depth=1 https://github.com/julianstorer/JUCE.git
git clone --depth=1 git@github.com:McMartin/JUCE.cmake.git
cd JUCE.cmake/extras/Projucer
mkdir build && cd build
cmake .. -G"Unix Makefiles" && make -j4
```

warnings generated: "NDEBUG or DEBUG has been defined - you should set one of these to make it clear whether this is a release build," [-W#warnings]
    #warning "Neither NDEBUG or DEBUG has been defined - you should set one of these to make it clear whether this is a release build,""

**Comment by McMartin** [comment]
You are missing the `BUILD_TYPE` when calling CMake:
```
cmake .. -DCMAKE_BUILD_TYPE=Debug
```
see https://github.com/McMartin/JUCE.cmake/blob/master/.travis.yml#L19.
