### ISSUE TITLE
The projucer app built with JUCE.cmake is not retina

### ISSUE THREAD

**Issue by MartyLake** [McMartin/JUCE.cmake#21]
<img width="1680" alt="screen shot 2016-12-20 at 09 56 10" src="https://cloud.githubusercontent.com/assets/1246794/21344162/a2d47ce0-c69a-11e6-9ac5-8531e91baf9b.png">

built with JUCE.camke = not retina

-----------------
<img width="1680" alt="screen shot 2016-12-20 at 09 56 33" src="https://cloud.githubusercontent.com/assets/1246794/21344161/a2d44aae-c69a-11e6-8c56-fc42fb816bd6.png">

built with JUCE = retina

**Comment by MartyLake** [comment]
I tried to modify the Info.plist to add the `High Resolution Capable` tag, with no success.

Joined file extension have been modified (added .txt) to support Github attachement restriction.
[Info JUCE.plist.txt](https://github.com/McMartin/JUCE.cmake/files/663183/Info.JUCE.plist.txt)
[Info JUCE.cmake modified.plist.txt](https://github.com/McMartin/JUCE.cmake/files/663184/Info.JUCE.cmake.modified.plist.txt)
[Info JUCE.cmake.plist.txt](https://github.com/McMartin/JUCE.cmake/files/663185/Info.JUCE.cmake.plist.txt)

**Comment by McMartin** [comment]
@MartyLake: I don't understand what the two screenshots are showing. Please add some legend.

**Comment by MartyLake** [comment]
Added legends

**Comment by McMartin** [comment]
I should have looked at the pictures in their original size, then it's obvious :smile:

**Comment by MartyLake** [comment]
Indeed ;-)

not important now , just for the record

**Comment by McMartin** [comment]
@MartyLake: #19 should have fixed this issue. Can you please try again with the latest `master`? Thanks!

**Comment by McMartin** [comment]
@MartyLake: ping

**Comment by MartyLake** [comment]
Issue fixed !
