### ISSUE TITLE
PkgInfo file for vst bundles.

### ISSUE THREAD

**Issue by WGuLL** [McMartin/JUCE.cmake#218]
Hi @McMartin !
It seems that the projucer is generating a pkginfo file automatically for VST and AU bundles.
According to this link: https://ccrma.stanford.edu/~kapilkm/220c/Vst_XCode.html:
```Create a blank text file in the ‘Resources’ section, put BNDL???? in it, and save it as PkgInfo. This is to make sure the OS X Finder sees the plugin as an actual executable, and not just another folder of stuff (which is what a bundle is, really).```
It would be a good thing if JUCE.cmake could setup the xcode project to generate this file in the VST and AU bundles automatically.

**Comment by McMartin** [comment]
Hi @WGuLL 

Indeed, `Projucer` sets the Xcode flag `GENERATE_PKGINFO_FILE = YES` for VST and AU targets. I'll have a look at what Xcode does exactly when this flag is set, and I will add that to `Reprojucer.cmake`.

Thanks for reporting!

**Comment by McMartin** [comment]
@WGuLL: I built `JuceDemoPlugin` using `Reprojucer.cmake`, and the VST bundle has a `PkgInfo` file with the expected content. The AU bundle doesn't have that file. Can you confirm that you are seeing the same thing with your plugin?
