### ISSUE TITLE
Renaming an app produced by JUCE.cmake breaks the app.

### ISSUE THREAD

**Issue by MartyLake** [McMartin/JUCE.cmake#22]
- build helloworld
- launch (OK)
- rename helloworldJUCECmake
- launch (NOK)

same steps only rename the application if built by JUCE.

**Comment by McMartin** [comment]
@MartyLake: I am not sure I understand completely. Do you mean renaming the app bundle? So here it would be renaming `HelloWorld.app` to something else?

**Comment by MartyLake** [comment]
Yes!

**Comment by McMartin** [comment]
@MartyLake: #19 may have fixed this issue. Can you please try again with the latest `master`? Thanks!

**Comment by McMartin** [comment]
@MartyLake: ping

**Comment by MartyLake** [comment]
Fixed !
