### ISSUE TITLE
Problem with prebuild script and post build script on Windows

### ISSUE THREAD

**Issue by Xav83** [McMartin/JUCE.cmake#246]
Hi @McMartin,
It seems that there is a problem with the prebuild and postbuild scripts on the Windows Toolchain, in Release Mode. The symptom is an invalid command line in the vcxproj file in the pre/post build script field:
`"" <path>\build\Release\postbuild_Release.cmd`
instead of
`call <path>\build\Release\postbuild_Release.cmd`.
We looked for the commit which trigger this bug, and found that [this commit]( https://github.com/McMartin/JUCE.cmake/commit/a443911e2f98f12860538c2a3d1318c7a7783f93) is responsible for the behavior. Especially the changes on the lines 1755 and 1809. Reversing the changes on those lines seems to fix the bug.

**Comment by McMartin** [comment]
Hi @Xav83,
Thank you very much for the very detailed problem description. Thank you even more for finding the origin of the bug. You rock!
#247 does what you expect.

**Comment by Xav83** [comment]
I reviewed the PR #247 and tried it on our project ! Everything works fine !
