### ISSUE TITLE
Add CMakeLists.txt files for JUCE/examples/PlugInSamples/*

### ISSUE THREAD

**Issue by McMartin** [McMartin/JUCE.cmake#48]
They should be similar to https://github.com/McMartin/JUCE.cmake/blob/master/examples/audio%20plugin%20demo/CMakeLists.txt

**Comment by MartyLake** [comment]
- [ ] Arpeggiator     
- [ ] GainPlugIn      
- [ ] MultiOutSynth   
- [ ] NoiseGate       
- [ ] Surround

**Comment by MartyLake** [comment]
WIP on branch https://github.com/McMartin/JUCE.cmake/tree/pluginSamplesExamples

**Comment by MartyLake** [comment]
Close by https://github.com/McMartin/JUCE.cmake/pull/50
