### ISSUE TITLE
Introduce .jucer -> CMakeLists.txt converter script

### ISSUE THREAD

**Issue by McMartin** [McMartin/JUCE.cmake#49]
Add a script called Jucer2CMake.cmake that takes the path to a .jucer project file as input and creates a corresponding CMakeLists.txt file.

This will enable fast adoption and testing in production: one can use Projucer and JUCE.cmake at the same time until they feel confident enough to go full CMake.

**Comment by McMartin** [comment]
Currently WIP on the branch [Jucer2CMake](https://github.com/McMartin/JUCE.cmake/tree/Jucer2CMake).

**Comment by MartyLake** [comment]
Should we mark it as done, as we can convert all the examples ? @McMartin

**Comment by McMartin** [comment]
In the end we didn't introduce a converter *script*, but a converter nonetheless, so let's close this.
