### ISSUE TITLE
The "Icon (small)" and "Icon (large)" exporter settings are not supported

### ISSUE THREAD

**Issue by MartyLake** [McMartin/JUCE.cmake#82]

**Comment by McMartin** [comment]
I did the work on `Jucer2Reprojucer` on the branch [`support-icon-settings`](https://github.com/McMartin/JUCE.cmake/tree/support-icon-settings), but we need to add an executable (`IconBuilder`) that converts `.png`  files into `.icns`  and `.ico`  files.
